language: python

dist: bionic
sudo: required

python:
  - 3.6
  - 3.5
  - 2.7

install:
  - sudo apt-get update
  - sudo apt-get install libpcap-dev
  - pip install -U tox-travis Cython

script: tox
